# Generated by Django 4.0.4 on 2022-09-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0002_corpusmetric'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassMetricRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.TextField()),
                ('cbo', models.IntegerField(blank=True, default=0, null=True)),
                ('ic', models.IntegerField(blank=True, default=0, null=True)),
                ('oc', models.IntegerField(blank=True, default=0, null=True)),
                ('cam', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=12, null=True)),
                ('nco', models.IntegerField(blank=True, default=0, null=True)),
                ('dit', models.IntegerField(blank=True, default=0, null=True)),
                ('rfc', models.IntegerField(blank=True, default=0, null=True)),
                ('loc', models.IntegerField(blank=True, default=0, null=True)),
                ('nca', models.IntegerField(blank=True, default=0, null=True)),
                ('project_id', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='CorpusMetric',
            new_name='CorpusFile',
        ),
        migrations.DeleteModel(
            name='Classes',
        ),
    ]
