# Generated by Django 4.0.4 on 2022-09-09 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0003_classmetricraw_rename_corpusmetric_corpusfile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='S101File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField(unique=True)),
                ('fileurl', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v2.project')),
            ],
        ),
    ]
