# Generated by Django 4.0.4 on 2022-09-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0004_s101file'),
    ]

    operations = [
        migrations.CreateModel(
            name='S101MetricRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_from', models.TextField(null=True)),
                ('usage', models.TextField(null=True)),
                ('class_to', models.TextField(null=True)),
                ('weight', models.IntegerField(default=0)),
                ('ok_from', models.IntegerField(default=0, null=True)),
                ('ok_to', models.IntegerField(default=0, null=True)),
                ('project_id', models.IntegerField()),
            ],
        ),
    ]
