# Generated by Django 4.0.4 on 2022-09-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0008_clusteringmetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpusfile',
            name='processing_time',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='s101file',
            name='processing_time',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
