# Generated by Django 4.0.4 on 2022-09-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0009_corpusfile_processing_time_s101file_processing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpusfile',
            name='processing_time',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='s101file',
            name='processing_time',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=12, null=True),
        ),
    ]
