# Generated by Django 4.0.4 on 2022-09-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0010_alter_corpusfile_processing_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusteringTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('algo', models.TextField()),
                ('processing_time', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
