# Generated by Django 4.0.4 on 2022-09-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0011_clusteringtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.TextField(null=True)),
                ('algo', models.TextField()),
                ('fileurl', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_id', models.IntegerField()),
            ],
        ),
    ]
