# Generated by Django 4.0.4 on 2022-09-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0012_graphimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphimages',
            name='processing_time',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=12, null=True),
        ),
    ]
