# Generated by Django 4.0.4 on 2022-09-21 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0014_clusteringnormalize_scoringaverage_scoringfinale'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField(unique=True)),
                ('fileurl', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('processing_time', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=12, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v2.project')),
            ],
        ),
    ]
