# Generated by Django 4.0.4 on 2022-11-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0015_completefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusteringtime',
            name='clustering_time',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=12, null=True),
        ),
    ]
