# Generated by Django 4.0.4 on 2022-12-01 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0017_scoringaverageall_scoringfinaleall'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScoringAverageAll',
        ),
    ]
