# Generated by Django 4.0.4 on 2023-04-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0020_alter_scoringfinaleall_acbm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringMedian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algo', models.TextField()),
                ('type', models.TextField(null=True)),
                ('cbm', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True)),
                ('wcbm', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True)),
                ('acbm', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True)),
                ('ncam', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True)),
                ('imc', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True)),
                ('nmo', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True)),
                ('trm', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True)),
                ('mloc', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True)),
                ('mnoc', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True)),
                ('mcd', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True)),
                ('project_id', models.IntegerField()),
            ],
        ),
    ]
