# Generated by Django 4.0.4 on 2023-04-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0021_scoringmedian'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringFinaleMedian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algo', models.TextField()),
                ('type', models.TextField(null=True)),
                ('cbm', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('wcbm', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('acbm', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('ncam', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('imc', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('nmo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('trm', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('mloc', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('mnoc', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('mcd', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('project_id', models.IntegerField()),
                ('coupling', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('cohesion', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('complexity', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('size', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
            ],
        ),
    ]
