# Generated by Django 4.0.4 on 2023-04-11 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0022_scoringfinalemedian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoringfinalemedian',
            name='cohesion',
        ),
        migrations.RemoveField(
            model_name='scoringfinalemedian',
            name='complexity',
        ),
        migrations.RemoveField(
            model_name='scoringfinalemedian',
            name='coupling',
        ),
        migrations.RemoveField(
            model_name='scoringfinalemedian',
            name='size',
        ),
        migrations.RemoveField(
            model_name='scoringfinalemedian',
            name='total',
        ),
    ]
