# Generated by Django 4.0.4 on 2023-04-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0024_scoringfinaleallmedian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoringfinaleall',
            name='acbm',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinaleall',
            name='cbm',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinaleall',
            name='cohesion',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinaleall',
            name='complexity',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinaleall',
            name='coupling',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinaleall',
            name='imc',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinaleall',
            name='mcd',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinaleall',
            name='mloc',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinaleall',
            name='mnoc',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinaleall',
            name='ncam',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinaleall',
            name='nmo',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinaleall',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinaleall',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinaleall',
            name='trm',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinaleall',
            name='wcbm',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinalemedian',
            name='acbm',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinalemedian',
            name='cbm',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinalemedian',
            name='imc',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinalemedian',
            name='mcd',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinalemedian',
            name='mloc',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinalemedian',
            name='mnoc',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinalemedian',
            name='ncam',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinalemedian',
            name='nmo',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinalemedian',
            name='trm',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinalemedian',
            name='wcbm',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True),
        ),
    ]
