# Generated by Django 4.0.4 on 2023-04-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0025_alter_scoringfinaleall_acbm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoringfinaleallmedian',
            name='acbm',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinaleallmedian',
            name='cbm',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinaleallmedian',
            name='imc',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinaleallmedian',
            name='mcd',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinaleallmedian',
            name='mloc',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinaleallmedian',
            name='mnoc',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinaleallmedian',
            name='ncam',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinaleallmedian',
            name='nmo',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinaleallmedian',
            name='trm',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinaleallmedian',
            name='wcbm',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True),
        ),
    ]
