# Generated by Django 4.0.4 on 2023-04-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0026_alter_scoringfinaleallmedian_acbm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringfinaleallmedian',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='scoringfinalemedian',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True),
        ),
    ]
