# Generated by Django 4.0.4 on 2023-04-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0027_scoringfinaleallmedian_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoringfinaleallmedian',
            name='total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinalemedian',
            name='total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
