# Generated by Django 4.0.4 on 2023-06-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0028_alter_scoringfinaleallmedian_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MsInteractions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ms_from', models.TextField()),
                ('ms_edge', models.IntegerField()),
                ('ms_to', models.TextField()),
                ('algo', models.TextField()),
                ('project_id', models.IntegerField()),
            ],
        ),
    ]
