# Generated by Django 4.0.4 on 2023-09-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0029_msinteractions'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringmedian',
            name='ideal',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='scoringmedian',
            name='ideal_d',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='scoringmedian',
            name='topsis_score',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='scoringmedian',
            name='worst',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='scoringmedian',
            name='worst_d',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True),
        ),
    ]
