# Generated by Django 4.0.4 on 2023-09-21 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0030_scoringmedian_ideal_scoringmedian_ideal_d_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoringmedian',
            name='ideal',
        ),
        migrations.RemoveField(
            model_name='scoringmedian',
            name='worst',
        ),
    ]
