# Generated by Django 4.0.4 on 2023-09-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0031_remove_scoringmedian_ideal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringmedian',
            name='tmp_count',
            field=models.IntegerField(default=0),
        ),
    ]
