# Generated by Django 4.0.4 on 2023-07-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassMetricRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.TextField()),
                ('cbo', models.IntegerField(blank=True, default=0, null=True)),
                ('ic', models.IntegerField(blank=True, default=0, null=True)),
                ('oc', models.IntegerField(blank=True, default=0, null=True)),
                ('cam', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=12, null=True)),
                ('nco', models.IntegerField(blank=True, default=0, null=True)),
                ('dit', models.IntegerField(blank=True, default=0, null=True)),
                ('rfc', models.IntegerField(blank=True, default=0, null=True)),
                ('loc', models.IntegerField(blank=True, default=0, null=True)),
                ('nca', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='S101MetricRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_from', models.TextField(null=True)),
                ('usage', models.TextField(null=True)),
                ('class_to', models.TextField(null=True)),
                ('weight', models.IntegerField(default=0)),
                ('ok_from', models.IntegerField(default=0, null=True)),
                ('ok_to', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
