# Generated by Django 4.0.4 on 2023-07-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0002_classmetricraw_s101metricraw'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricNormalize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.TextField()),
                ('cbo', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True)),
                ('ic', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True)),
                ('oc', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True)),
                ('cam', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True)),
                ('nco', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True)),
                ('dit', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True)),
                ('rfc', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True)),
                ('loc', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True)),
                ('nca', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True)),
            ],
        ),
    ]
