# Generated by Django 4.0.4 on 2023-07-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0003_metricnormalize'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clustering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.TextField()),
                ('cluster', models.IntegerField()),
                ('project_id', models.IntegerField()),
            ],
        ),
    ]
