# Generated by Django 4.0.4 on 2023-07-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0005_clustering_cam_clustering_cbo_clustering_dit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clustering',
            name='cam',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='clustering',
            name='cbo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='clustering',
            name='dit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='clustering',
            name='ic',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='clustering',
            name='loc',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='clustering',
            name='nca',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='clustering',
            name='nco',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='clustering',
            name='oc',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='clustering',
            name='rfc',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
