# Generated by Django 4.0.4 on 2023-07-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0006_alter_clustering_cam_alter_clustering_cbo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusteringMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('microservice', models.IntegerField()),
                ('cbm', models.IntegerField(default=0)),
                ('wcbm', models.IntegerField(default=0)),
                ('acbm', models.IntegerField(default=0)),
                ('ncam', models.DecimalField(decimal_places=6, default=0, max_digits=30)),
                ('imc', models.IntegerField(default=0)),
                ('nmo', models.IntegerField(default=0)),
                ('trm', models.IntegerField(default=0)),
                ('mloc', models.IntegerField(default=0)),
                ('mnoc', models.IntegerField(default=0)),
                ('is_ned', models.IntegerField(default=0)),
                ('project_id', models.IntegerField()),
            ],
        ),
    ]
