# Generated by Django 4.0.4 on 2023-07-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0007_clusteringmetric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clustering',
            name='cam',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='clustering',
            name='cbo',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='clustering',
            name='dit',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='clustering',
            name='ic',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='clustering',
            name='loc',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='clustering',
            name='nca',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='clustering',
            name='nco',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='clustering',
            name='oc',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='clustering',
            name='rfc',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True),
        ),
    ]
