# Generated by Django 4.0.4 on 2023-07-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0008_alter_clustering_cam_alter_clustering_cbo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusteringNormalize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('microservice', models.IntegerField()),
                ('cbm', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True)),
                ('wcbm', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True)),
                ('acbm', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True)),
                ('ncam', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True)),
                ('imc', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True)),
                ('nmo', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True)),
                ('trm', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True)),
                ('mloc', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True)),
                ('mnoc', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True)),
                ('project_id', models.IntegerField()),
            ],
        ),
    ]
