# Generated by Django 4.0.4 on 2023-07-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0010_scoringmedian'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringFinaleMedian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbm', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True)),
                ('wcbm', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True)),
                ('acbm', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True)),
                ('ncam', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True)),
                ('imc', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True)),
                ('nmo', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True)),
                ('trm', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True)),
                ('mloc', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True)),
                ('mnoc', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True)),
                ('mcd', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True)),
                ('total', models.IntegerField(blank=True, default=0, null=True)),
                ('project_id', models.IntegerField()),
            ],
        ),
    ]
