# Generated by Django 4.0.4 on 2023-07-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0011_scoringfinalemedian'),
    ]

    operations = [
        migrations.CreateModel(
            name='MsInteractions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ms_from', models.TextField()),
                ('ms_edge', models.IntegerField()),
                ('ms_to', models.TextField()),
                ('project_id', models.IntegerField()),
            ],
        ),
    ]
