# Generated by Django 4.0.4 on 2023-09-22 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0015_scoringmedian_ideal_d_scoringmedian_topsis_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoringfinalemedian',
            name='ideal_d',
        ),
        migrations.RemoveField(
            model_name='scoringfinalemedian',
            name='topsis_score',
        ),
        migrations.RemoveField(
            model_name='scoringfinalemedian',
            name='worst_d',
        ),
    ]
