# Generated by Django 4.0.4 on 2022-04-17 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClocMetricRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.TextField()),
                ('comment', models.IntegerField()),
                ('code', models.IntegerField()),
                ('ok', models.IntegerField(default=0, null=True)),
                ('project_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Clustering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.TextField()),
                ('cluster', models.IntegerField()),
                ('type', models.TextField()),
                ('algo', models.TextField()),
                ('project_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClusteringMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algo', models.TextField()),
                ('microservice', models.TextField()),
                ('cbm', models.IntegerField(default=0)),
                ('wcbm', models.IntegerField(default=0)),
                ('acbm', models.IntegerField(default=0)),
                ('ncam', models.DecimalField(decimal_places=6, default=0, max_digits=30)),
                ('imc', models.IntegerField(default=0)),
                ('nmo', models.IntegerField(default=0)),
                ('trm', models.IntegerField(default=0)),
                ('mloc', models.IntegerField(default=0)),
                ('mnoc', models.IntegerField(default=0)),
                ('project_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GraphImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algo', models.TextField()),
                ('fileurl', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MetricNormalize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.TextField()),
                ('cbo', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True)),
                ('ic', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True)),
                ('oc', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True)),
                ('cam', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True)),
                ('nco', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True)),
                ('dit', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True)),
                ('rfc', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True)),
                ('loc', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True)),
                ('nca', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True)),
                ('normalized', models.IntegerField(default=0)),
                ('project_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NetworkMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algo', models.TextField()),
                ('microservice', models.TextField()),
                ('cbm', models.IntegerField(default=0)),
                ('wcbm', models.IntegerField(default=0)),
                ('acbm', models.IntegerField(default=0)),
                ('ncam', models.DecimalField(decimal_places=6, default=0, max_digits=30)),
                ('imc', models.IntegerField(default=0)),
                ('nmo', models.IntegerField(default=0)),
                ('trm', models.IntegerField(default=0)),
                ('mloc', models.IntegerField(default=0)),
                ('mnoc', models.IntegerField(default=0)),
                ('project_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='S101MetricRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_from', models.TextField(null=True)),
                ('usage', models.TextField(null=True)),
                ('class_to', models.TextField(null=True)),
                ('weight', models.IntegerField(default=0)),
                ('ok_from', models.IntegerField(default=0, null=True)),
                ('ok_to', models.IntegerField(default=0, null=True)),
                ('project_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SdMetricRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.TextField()),
                ('cbo', models.IntegerField(blank=True, default=0, null=True)),
                ('ic', models.IntegerField(blank=True, default=0, null=True)),
                ('oc', models.IntegerField(blank=True, default=0, null=True)),
                ('cam', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=12, null=True)),
                ('nco', models.IntegerField(blank=True, default=0, null=True)),
                ('dit', models.IntegerField(blank=True, default=0, null=True)),
                ('rfc', models.IntegerField(blank=True, default=0, null=True)),
                ('loc', models.IntegerField(blank=True, default=0, null=True)),
                ('nca', models.IntegerField(blank=True, default=0, null=True)),
                ('project_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SdMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField(unique=True)),
                ('fileurl', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squality.project')),
            ],
        ),
        migrations.CreateModel(
            name='S101Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField(unique=True)),
                ('fileurl', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squality.project')),
            ],
        ),
        migrations.CreateModel(
            name='ClocMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField(unique=True)),
                ('fileurl', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squality.project')),
            ],
        ),
    ]
