# Generated by Django 4.0.4 on 2022-04-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.TextField()),
                ('cluster', models.IntegerField()),
                ('type', models.TextField()),
                ('algo', models.TextField()),
                ('project_id', models.IntegerField()),
            ],
        ),
    ]
