# Generated by Django 4.0.4 on 2022-04-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricSdRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.TextField()),
                ('cbo', models.DecimalField(decimal_places=8, max_digits=9)),
                ('ic', models.DecimalField(decimal_places=8, max_digits=9)),
                ('oc', models.DecimalField(decimal_places=8, max_digits=9)),
                ('cam', models.DecimalField(decimal_places=8, max_digits=9)),
                ('nco', models.DecimalField(decimal_places=8, max_digits=9)),
                ('dit', models.DecimalField(decimal_places=8, max_digits=9)),
                ('rfc', models.DecimalField(decimal_places=8, max_digits=9)),
                ('loc', models.DecimalField(decimal_places=8, max_digits=9)),
                ('nca', models.DecimalField(decimal_places=8, max_digits=9)),
                ('project_id', models.IntegerField()),
            ],
        ),
    ]
