# Generated by Django 4.0.4 on 2022-04-13 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squality', '0002_metricsdraw'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MetricSdRaw',
            new_name='SdMetricRaw',
        ),
    ]
