# Generated by Django 4.0.4 on 2022-04-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squality', '0002_networkcluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphimages',
            name='fullname',
            field=models.TextField(null=True),
        ),
    ]
