# Generated by Django 4.0.4 on 2022-04-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squality', '0003_rename_metricsdraw_sdmetricraw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='s101metric',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sdmetric',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
