# Generated by Django 4.0.4 on 2022-04-17 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squality', '0003_graphimages_fullname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NetworkCluster',
        ),
    ]
