# Generated by Django 4.0.4 on 2022-04-17 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squality', '0004_delete_networkcluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusteringmetric',
            name='type',
            field=models.TextField(null=True),
        ),
    ]
