# Generated by Django 4.0.4 on 2022-04-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squality', '0004_alter_project_created_at_alter_s101metric_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdmetricraw',
            name='cam',
            field=models.DecimalField(decimal_places=10, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sdmetricraw',
            name='cbo',
            field=models.DecimalField(decimal_places=10, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sdmetricraw',
            name='dit',
            field=models.DecimalField(decimal_places=10, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sdmetricraw',
            name='ic',
            field=models.DecimalField(decimal_places=10, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sdmetricraw',
            name='loc',
            field=models.DecimalField(decimal_places=10, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sdmetricraw',
            name='nca',
            field=models.DecimalField(decimal_places=10, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sdmetricraw',
            name='nco',
            field=models.DecimalField(decimal_places=10, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sdmetricraw',
            name='oc',
            field=models.DecimalField(decimal_places=10, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sdmetricraw',
            name='rfc',
            field=models.DecimalField(decimal_places=10, max_digits=12),
        ),
    ]
