# Generated by Django 4.0.4 on 2022-04-17 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squality', '0005_clusteringmetric_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NetworkMetric',
        ),
    ]
