# Generated by Django 4.0.4 on 2022-04-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squality', '0005_alter_sdmetricraw_cam_alter_sdmetricraw_cbo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdmetricraw',
            name='cbo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sdmetricraw',
            name='dit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sdmetricraw',
            name='ic',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sdmetricraw',
            name='loc',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sdmetricraw',
            name='nca',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sdmetricraw',
            name='nco',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sdmetricraw',
            name='oc',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sdmetricraw',
            name='rfc',
            field=models.IntegerField(),
        ),
    ]
