# Generated by Django 4.0.4 on 2022-04-14 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('squality', '0006_alter_sdmetricraw_cbo_alter_sdmetricraw_dit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClocMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField(unique=True)),
                ('fileurl', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squality.project')),
            ],
        ),
    ]
