# Generated by Django 4.0.4 on 2022-04-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squality', '0007_clocmetric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdmetricraw',
            name='cam',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='sdmetricraw',
            name='cbo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sdmetricraw',
            name='dit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sdmetricraw',
            name='ic',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sdmetricraw',
            name='loc',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sdmetricraw',
            name='nca',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sdmetricraw',
            name='nco',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sdmetricraw',
            name='oc',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sdmetricraw',
            name='rfc',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
