# Generated by Django 4.0.4 on 2022-04-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squality', '0008_alter_sdmetricraw_cam_alter_sdmetricraw_cbo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClocMetricRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.TextField()),
                ('comment', models.IntegerField()),
                ('code', models.IntegerField()),
                ('project_id', models.IntegerField()),
            ],
        ),
    ]
