# Generated by Django 4.0.4 on 2022-04-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squality', '0009_clocmetricraw'),
    ]

    operations = [
        migrations.CreateModel(
            name='S101MetricRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_from', models.TextField()),
                ('usage', models.TextField()),
                ('class_to', models.TextField()),
                ('weight', models.IntegerField(default=0)),
                ('project_id', models.IntegerField()),
            ],
        ),
    ]
