# Generated by Django 4.0.4 on 2022-04-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squality', '0010_s101metricraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='clocmetricraw',
            name='ok',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
