# Generated by Django 4.0.4 on 2022-04-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squality', '0010_alter_clusteringmetric_microservice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringfinale',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=30, null=True),
        ),
    ]
