# Generated by Django 4.0.4 on 2022-04-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squality', '0011_scoringfinale_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoringfinale',
            name='acbm',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinale',
            name='cbm',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinale',
            name='imc',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinale',
            name='mloc',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinale',
            name='mnoc',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinale',
            name='ncam',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinale',
            name='nmo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinale',
            name='total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinale',
            name='trm',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinale',
            name='wcbm',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
