# Generated by Django 4.0.4 on 2022-04-15 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squality', '0012_s101metricraw_ok'),
    ]

    operations = [
        migrations.RenameField(
            model_name='s101metricraw',
            old_name='ok',
            new_name='ok_from',
        ),
        migrations.AddField(
            model_name='s101metricraw',
            name='ok_to',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
