# Generated by Django 4.0.4 on 2022-05-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squality', '0012_alter_scoringfinale_acbm_alter_scoringfinale_cbm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusteringmetric',
            name='is_ned',
            field=models.IntegerField(default=0),
        ),
    ]
