# Generated by Django 4.0.4 on 2022-04-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squality', '0013_rename_ok_s101metricraw_ok_from_s101metricraw_ok_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricNormalize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.TextField()),
                ('cbo', models.IntegerField(blank=True, default=0, null=True)),
                ('ic', models.IntegerField(blank=True, default=0, null=True)),
                ('oc', models.IntegerField(blank=True, default=0, null=True)),
                ('cam', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=12, null=True)),
                ('nco', models.IntegerField(blank=True, default=0, null=True)),
                ('dit', models.IntegerField(blank=True, default=0, null=True)),
                ('rfc', models.IntegerField(blank=True, default=0, null=True)),
                ('loc', models.IntegerField(blank=True, default=0, null=True)),
                ('nca', models.IntegerField(blank=True, default=0, null=True)),
                ('project_id', models.IntegerField()),
            ],
        ),
    ]
