# Generated by Django 4.0.4 on 2022-05-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squality', '0016_alter_scoringfinale_acbm_alter_scoringfinale_cbm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoringfinale',
            name='acbm',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinale',
            name='cbm',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinale',
            name='imc',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinale',
            name='mcd',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinale',
            name='mloc',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinale',
            name='mnoc',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinale',
            name='ncam',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinale',
            name='nmo',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinale',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinale',
            name='trm',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='scoringfinale',
            name='wcbm',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=9, null=True),
        ),
    ]
