# Generated by Django 4.0.4 on 2022-06-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squality', '0017_alter_scoringfinale_acbm_alter_scoringfinale_cbm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdmetricraw',
            name='xmi_id',
            field=models.TextField(default='xmi.id'),
            preserve_default=False,
        ),
    ]
