# Generated by Django 4.0.4 on 2022-06-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squality', '0019_eametric'),
    ]

    operations = [
        migrations.CreateModel(
            name='EaMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.TextField()),
                ('method_name', models.TextField()),
                ('project_id', models.IntegerField()),
            ],
        ),
    ]
