# Generated by Django 4.0.4 on 2022-06-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squality', '0020_eamethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricnormalize',
            name='xmi_id',
            field=models.TextField(default='default-value'),
            preserve_default=False,
        ),
    ]
