# Generated by Django 4.0.4 on 2022-04-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squality', '0020_clustering'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusteringMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algo', models.TextField()),
                ('microservice', models.TextField()),
                ('cbm', models.IntegerField(default=0)),
                ('wcbm', models.IntegerField(default=0)),
                ('acbm', models.IntegerField(default=0)),
                ('ncam', models.DecimalField(decimal_places=6, default=0, max_digits=30)),
                ('imc', models.IntegerField(default=0)),
                ('nmo', models.IntegerField(default=0)),
                ('trm', models.IntegerField(default=0)),
                ('mloc', models.IntegerField(default=0)),
                ('mnoc', models.IntegerField(default=0)),
                ('project_id', models.IntegerField()),
            ],
        ),
    ]
