# Generated by Django 4.0.4 on 2022-04-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squality', '0021_clusteringmetric'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField()),
                ('target', models.TextField()),
                ('weight', models.IntegerField()),
                ('algo', models.TextField()),
                ('project_id', models.IntegerField()),
            ],
        ),
    ]
