# Generated by Django 4.0.4 on 2022-06-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squality', '0022_clustering_xmi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='eamethod',
            name='xmi_id',
            field=models.TextField(default='default-value'),
            preserve_default=False,
        ),
    ]
