# Generated by Django 4.0.4 on 2022-04-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squality', '0022_networkmetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkmetric',
            name='source_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='networkmetric',
            name='target_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='networkmetric',
            name='algo',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='networkmetric',
            name='project_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='networkmetric',
            name='source',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='networkmetric',
            name='target',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='networkmetric',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
