# Generated by Django 4.0.4 on 2022-04-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squality', '0023_networkmetric_source_id_networkmetric_target_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='filename',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='fileurl',
            field=models.TextField(null=True),
        ),
    ]
