# Generated by Django 4.0.4 on 2022-07-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squality', '0023_eamethod_xmi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringfinale',
            name='cohesion',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='scoringfinale',
            name='complexity',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='scoringfinale',
            name='coupling',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='scoringfinale',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=9, null=True),
        ),
    ]
